version: '2'

services:
  nginx:
    build: ./containers/nginx
    container_name: pr-nginx
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime/:ro
      - ./logs:/var/log/nginx
      - ./src/frontend:/var/www
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: nginx -g "daemon off;"
    restart: always
  frontend:
    build: ./src/frontend
    container_name: pr-frontend
    volumes:
      - ./src/frontend:/var/www
      - ./logs:/var/log/fpm
      - /etc/passwd:/etc/passwd/:ro
      - /etc/group:/etc/group/:ro
    restart: always
  backup:
    build: ./src/backup-runner/
    container_name: pr-backup
    volumes:
      - ./src/backup:/app/service
      - ./src/backup-runner/:/app/runner
      - ./logs:/var/log/php
      - /mnt/b/backup:/mnt/b/backup
    restart: always
  mongo:
    image: mongo:3-stretch
    container_name: pr-mongodb
    hostname: pr-mongodb
    volumes:
      - ./data/mongo:/data/db
    restart: always
    entrypoint:
      mongod --bind_ip_all
  rabbitmq:
    image: rabbitmq:3-management
    hostname: pr-rabbitmq
    container_name: pr-rabbitmq
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    restart: always
